# -*- coding: utf-8 -*-
"""
Schema Version Checks
"""

from __future__ import annotations
from src.validation.models import ValidationArtifacts
from src.validation.report import add_check, add_finding

def check_schema_versions(artifacts: ValidationArtifacts, report: dict) -> None:
    """Validate artifact schema versions against specifications."""
    strict = report.get("strict", False)
    
    findings_added = 0
    checks_run = 0
    
    # 1. source_reconstruction.json
    if artifacts.source_reconstruction is not None:
        checks_run += 1
        ver = artifacts.source_reconstruction.get("schema_version")
        if ver != "5.7.2":
            findings_added += 1
            add_finding(
                report=report,
                finding_id="VAL-SCHM-001",
                severity="error",
                category="schema",
                title="Invalid source_reconstruction.json schema version",
                message=f"Expected schema version '5.7.2', found '{ver}'.",
                artifact="source_reconstruction.json",
                evidence={"observed": ver, "expected": "5.7.2"},
                recommendation="Ensure source_reconstruction artifact is generated by Phase 5.7.2 or later."
            )
            
    # 2. pipeline_manifest.json
    if artifacts.pipeline_manifest is not None:
        checks_run += 1
        ver = artifacts.pipeline_manifest.get("schema_version")
        if ver != "pipeline-1.0":
            findings_added += 1
            severity = "error" if strict else "warning"
            add_finding(
                report=report,
                finding_id="VAL-SCHM-002",
                severity=severity,
                category="schema",
                title="Invalid pipeline_manifest.json schema version",
                message=f"Expected schema version 'pipeline-1.0', found '{ver}'.",
                artifact="pipeline_manifest.json",
                evidence={"observed": ver, "expected": "pipeline-1.0"},
                recommendation="Regenerate the pipeline manifest using Phase 5.8 End-to-End runner."
            )
            if strict:
                report["findings"][-1]["strict_promoted"] = True
                
    # 3. unified_ir.json
    if artifacts.unified_ir is not None:
        checks_run += 1
        ver = artifacts.unified_ir.get("schema_version")
        if ver != "2.0.0":
            findings_added += 1
            severity = "error" if strict else "warning"
            add_finding(
                report=report,
                finding_id="VAL-SCHM-003",
                severity=severity,
                category="schema",
                title="Invalid unified_ir.json schema version",
                message=f"Expected schema version '2.0.0', found '{ver}'.",
                artifact="unified_ir.json",
                evidence={"observed": ver, "expected": "2.0.0"},
                recommendation="Ensure the extractor compiles unified_ir.json with schema 2.0.0."
            )
            if strict:
                report["findings"][-1]["strict_promoted"] = True
                
    # 4. phase4_semantics.json
    if artifacts.phase4_semantics is not None:
        checks_run += 1
        ver = artifacts.phase4_semantics.get("schema_version")
        if ver != "4D.1.0":
            findings_added += 1
            severity = "error" if strict else "warning"
            add_finding(
                report=report,
                finding_id="VAL-SCHM-004",
                severity=severity,
                category="schema",
                title="Invalid phase4_semantics.json schema version",
                message=f"Expected schema version '4D.1.0', found '{ver}'.",
                artifact="phase4_semantics.json",
                evidence={"observed": ver, "expected": "4D.1.0"},
                recommendation="Verify that Phase 4D semantics recovery outputs schema version '4D.1.0'."
            )
            if strict:
                report["findings"][-1]["strict_promoted"] = True
                
    # Add check summary
    if findings_added > 0:
        has_error = any(f["severity"] == "error" for f in report["findings"][-findings_added:])
        status = "failed" if has_error else "warning"
        msg = f"Completed {checks_run} schema checks. Found {findings_added} invalid versions."
    else:
        status = "ok"
        msg = "Artifact schema versions are valid."
        
    add_check(
        report=report,
        name="schema_versions_valid",
        status=status,
        severity="error",
        message=msg
    )
